src/main/java/GoodGenerator/Loader/RecipeLoader.java, src/main/java/GoodGenerator/Main/GoodGenerator.java
add Gradle  GRADLETOKEN_VERSION
=> change eu values a bit

src/main/java/GoodGenerator/Blocks/TEs/MetaTE/NeutronSensor.java, src/main/java/GoodGenerator/Client/GUI/NeutronSensorGUIClient.java, src/main/java/GoodGenerator/Main/GoodGenerator.java, src/main/java/GoodGenerator/Network/MessageMTEBase.java, src/main/java/GoodGenerator/Network/MessageOpenNeutronSensorGUI.java, src/main/java/GoodGenerator/Network/MessageSetNeutronSensorData.java
Upon repo owner's request I have made a patch to make the changes done in gui to sync between server and client properly. I have no idea whether the underlying logic, e.g. expression parsing, works correctly though.
=> Fix NeutronSensor GUI sync

.editorconfig, .github/scripts/test-no-error-reports.sh, .github/workflows/build-and-test.yml, README.md, build.gradle, dependencies.gradle, repositories.gradle, src/main/java/goodgenerator/blocks/tileEntity/ExtremeHeatExchanger.java, src/main/java/goodgenerator/blocks/tileEntity/FuelRefineFactory.java, src/main/java/goodgenerator/blocks/tileEntity/LargeEssentiaGenerator.java, src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer.java, src/main/java/goodgenerator/blocks/tileEntity/MegaPlasmaTurbine.java, src/main/java/goodgenerator/blocks/tileEntity/MultiNqGenerator.java, src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java, src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java, src/main/java/goodgenerator/blocks/tileEntity/UniversalChemicalFuelEngine.java, src/main/java/goodgenerator/blocks/tileEntity/YottaFluidTank.java, src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java, src/main/java/goodgenerator/main/GoodGenerator.java, src/main/resources/mcmod.info
updated buildscript pulled in new tectech which removed deprecated scructurelib stuff.
also a call apparently has been flipped
added dependencies for runServer
=> Fixstructurelib

src/main/java/goodgenerator/items/MyMaterial.java, src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java, src/main/java/goodgenerator/loader/RecipeLoader.java, src/main/java/goodgenerator/loader/RecipeLoader_02.java
- nerf the NOM dust directly to Nq nuggets recipe
- a compact recipe for fluoroantimonic acid
- make calcium 100% recycled
=> few naqline recipe change

dependencies.gradle, src/main/java/goodgenerator/loader/Loaders.java, src/main/java/goodgenerator/loader/RecipeLoader_02.java, src/main/java/goodgenerator/util/MaterialFix.java
fix some self-locked recipe and missing recipes for some material parts
=> Recipe fix

src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
- reduce the sulfuric acid consumption
- nerf trinium from trinium sulphate
- fully recyclied zinc
=> rebalance enrich nq line

src/main/java/goodgenerator/blocks/tileEntity/SupercriticalFluidTurbine.java, src/main/java/goodgenerator/loader/RecipeLoader_02.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9956#issuecomment-1067651927
=> fix oversight on sc turbine energy cal and water amount dispaly

src/main/java/goodgenerator/loader/RecipeLoader_02.java
Needs to be turned off until https://github.com/GTNewHorizons/GTplusplus/pull/115 is done by @draknyte1
=> Disable MK5 compact fusion recipe

dependencies.gradle, src/main/java/goodgenerator/blocks/tileEntity/ExtremeHeatExchanger.java, src/main/java/goodgenerator/blocks/tileEntity/FuelRefineFactory.java, src/main/java/goodgenerator/blocks/tileEntity/LargeEssentiaGenerator.java, src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer1.java, src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer2.java, src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer3.java, src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer4.java, src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer5.java, src/main/java/goodgenerator/blocks/tileEntity/MultiNqGenerator.java, src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java, src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java, src/main/java/goodgenerator/blocks/tileEntity/UniversalChemicalFuelEngine.java, src/main/java/goodgenerator/blocks/tileEntity/YottaFluidTank.java, src/main/java/goodgenerator/blocks/tileEntity/base/GT_MetaTileEntity_TooltipMultiBlockBase_EM.java, src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java, src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputerPP.java
Please refer to GTNewHorizons/GT-New-Horizons-Modpack#9989
=> Fix secondary description not written to language file

src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/NeutronAccelerator.java, src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java, src/main/java/goodgenerator/loader/RecipeLoader_02.java
i am not sure whether this fix can work, let's pray for it
=> attempt to fix NA in thermos

src/main/java/goodgenerator/crossmod/nei/IMCForNEI.java
requires https://github.com/GTNewHorizons/NotEnoughItems/pull/232 to work
some of the catalysts are already in NEI jar
=> Add some NEI catalysts

src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
otherwise it will try to drain more energy than it should
=> use the correct max input power method

src/main/java/goodgenerator/main/GoodGenerator.java
oversight in ctrl c/v
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10206
=> fix the same message id

src/main/java/goodgenerator/loader/RecipeLoader.java
KNO3 =  KNO3
(cherry picked from commit e4e904dc876229eb8174fce4bc33900f02bc8e66)
=> change PotassiumNitrate to Salpeter

src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10464
=> correct tooltip

dependencies.gradle, src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
Fix it cannot overclock with 2 energy hatches like other multis
=> Use getMaxInputVoltage for finding recipes in Precise Assembler

src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
Context: https://discord.com/channels/181078474394566657/522098956491030558/987876214469455943 and https://discord.com/channels/181078474394566657/401118216228831252/987899848953049128
=> Limit PASS recipes by energy hatch tier as well

dependencies.gradle, src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10577
=> use correctt silicon for boule

src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
Context: https://github.com/GTNewHorizons/GT5-Unofficial/pull/1135
=> Don't modify unrelated recipes

src/main/java/goodgenerator/loader/RecipeLoader_02.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10942
=> Fix overflow with EHE

dependencies.gradle, src/main/java/goodgenerator/loader/RecipeLoader_02.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10967
=> Fix exploit with disassembler

src/main/java/goodgenerator/blocks/tileEntity/YottaFluidTank.java
Changed Fluid Display to display it nicer and bigger for monitors
=> Changed Fluid Display

src/main/java/goodgenerator/items/MyMaterial.java
It can be used for silicon line
=> Enable electrolyzing Zinc Chloride

src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11272
=> fix voltage check

src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11320
=> fix overflow cal when max input voltage over max

build.gradle, src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
This matches TT behaviour of the private cyclicUpdate() function in TT machines.
See <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11315>
=> Reset mUpdate timer when base cyclicUpdate_EM() is triggered

src/main/java/goodgenerator/blocks/tileEntity/LargeEssentiaSmeltery.java, src/main/java/goodgenerator/blocks/tileEntity/base/GT_MetaTileEntity_TooltipMultiBlockBase_EM.java
close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11405
=> Fix pollution produce

src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java
Added start and end processing calls to NA onPostTick item access
=> Fix possible dupe bug in NA

src/main/java/goodgenerator/items/MyMaterial.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9950
=> Disable autogenerating Dalisenite smelting recipes

src/main/java/goodgenerator/loader/RecipeLoader_02.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11564
=> Fix incorrect material used for YotTank AL recipes

src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11657
=> fix missing hatch element

dependencies.gradle, src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/YOTTAHatch.java, src/main/java/goodgenerator/blocks/tileEntity/YottaFluidTank.java
- fix yottank can't form with certain glass
- fix yothatch lag in a proper way
- allow yothatch can access up to max long amount fluids
- allow yothatch can i/o up to max long amount fluids
working:
idle:
=> fix bunch of yottank issues

src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
0.03 mm changed to 7nm. A "precise assembler" should be more precise than that :)
=> Slightly change the Precise assembler tooltip

src/main/java/goodgenerator/items/FuelRod.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11328
=> fix 0 stack of nuclear rod

src/main/java/goodgenerator/blocks/tileEntity/FuelRefineFactory.java, src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java, src/main/java/goodgenerator/loader/RecipeLoader.java
1. remove the magic materials from the atomic separation catalyst
2. make naqudah refinery actually gated at uhv
=> naq fuel change

src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
=> fix free sodium

.gitignore, src/main/java/goodgenerator/items/MyMaterial.java
Need these materials to have dense plates for some of the QFT's casing recipes
=> Add Some dense plates for materials

src/main/java/goodgenerator/loader/RecipeLoader_02.java
ID 31076 is used by XL Turbo SC Steam Turbine
=> Fix recipe for Compact Fusion IV

dependencies.gradle, src/main/java/goodgenerator/items/MyMaterial.java, src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
naq in uev, enriched naq in uiv and naquadria in umv
process the inert dust in neutron activator with plasma
=> naq line skip

src/main/java/goodgenerator/loader/ComponentAssemblyLineMiscRecipes.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11964
I don't think its needed for the CoAL to use assline controller for its research
=> fix research incompatability

src/main/java/goodgenerator/loader/RecipeLoader.java
resolves https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12066
=> Add recipe to recycle SodiumNitrate

src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12198
=> fix compact fusion scanner info display error

src/main/java/goodgenerator/blocks/tileEntity/SupercriticalFluidTurbine.java, src/main/java/goodgenerator/blocks/tileEntity/base/GT_MetaTileEntity_LargeTurbineBase.java
close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12223
=> make sc turbine won't explode when overvoltaged

src/main/java/goodgenerator/loader/ComponentAssemblyLineMiscRecipes.java, src/main/java/goodgenerator/loader/RecipeLoader.java, src/main/java/goodgenerator/loader/RecipeLoader_02.java
=> Nano -> any UIV

src/main/java/goodgenerator/loader/RecipeLoader_02.java
=> Add alternative recipe to goodgen circuits using rotors

src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java, src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputerPP.java
Proper fix to NPE that mc7771 tried to fix in https://github.com/GTNewHorizons/GoodGenerator/pull/145
=> Fix-Compact-Fusion

src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java
- Improved tooltip
- Make the naq-skip recipes doable with normal input busses
- Save memory
=> Various NA fixes

src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java, src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputerPP.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13086
=> Allow ME output hatch in compacts

src/main/java/goodgenerator/blocks/tileEntity/ComponentAssemblyLine.java
…n from MadMan, will allow for faster automation to help prevent spamming them.
Just allows for 2 more input buses, good for automation.
Got permission from MadMan, tested in dev instance, multi formed with new buses and without, no problems.
=> More CoAl fixes

src/main/java/goodgenerator/loader/RecipeLoader_02.java
Requires https://github.com/GTNewHorizons/GT5-Unofficial/pull/1855
=> Kill Disassembler in GoodGenerator

build.gradle, dependencies.gradle, src/main/java/goodgenerator/loader/ComponentAssemblyLineMiscRecipes.java, src/main/java/goodgenerator/loader/FuelRecipeLoader.java, src/main/java/goodgenerator/loader/RecipeLoader.java, src/main/java/goodgenerator/loader/RecipeLoader_02.java, src/main/java/goodgenerator/util/StackUtils.java
Need this pr
* https://github.com/GTNewHorizons/GT5-Unofficial/pull/1893
=> Fix Materials

build.gradle, dependencies.gradle, src/main/java/goodgenerator/blocks/tileEntity/ExtremeHeatExchanger.java, src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java
* bs
* any glass for ExtremeHeatExchanger
* any glass for NeutronActivator
=> any glass for structures

src/main/java/goodgenerator/blocks/tileEntity/CoolantTower.java
Also reduce recipe time to 1s because 5s of steam from an XL turbine is A LOT.
Fixes: GTNewHorizons/GT-New-Horizons-Modpack#12104.
=> Coolant Tower: pull steam from all available hatches.

src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/YOTTAHatch.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13939
=> Fix YOTTA not voiding fluids that are inserted through AE

src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
https://discord.com/channels/181078474394566657/603348502637969419/1131506106041118770
=> Replace mEUStore with getStoredEU call

src/main/java/goodgenerator/blocks/tileEntity/YottaFluidTank.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14018
=> fix divide by zero

.gitignore, dependencies.gradle, src/main/java/goodgenerator/blocks/tileEntity/FuelRefineFactory.java, src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java, src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java, src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
Requires https://github.com/GTNewHorizons/GT5-Unofficial/pull/2185
=> Use new API from GT5u

dependencies.gradle, src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java
This fixes neutron activators outputting nothing and consuming inputs
=> Fix neutron activators getting to 0 ticks

build.gradle, src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14158
=> Fix Compact Fusion not showing correct parallel for scanner

src/main/java/goodgenerator/blocks/tileEntity/FuelRefineFactory.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14234
=> Fix fuel refinery overclocks

src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14374 
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14375
=> Fix precise assembler not overclocking with amperage and Precise mode having parallels

src/main/java/goodgenerator/blocks/tileEntity/MultiNqGenerator.java
=> Fix Large Naq Reactor tooltip error

src/main/java/goodgenerator/items/MyItemBlocks.java, src/main/resources/assets/goodgenerator/lang/en_US.lang, src/main/resources/assets/goodgenerator/lang/zh_CN.lang
add the word "yottank" to the fluid cells' tooltip so they can be found easily in NEI
=> Fluid cell tooltip change

src/main/java/goodgenerator/blocks/tileEntity/ComponentAssemblyLine.java, src/main/java/goodgenerator/blocks/tileEntity/CoolantTower.java, src/main/java/goodgenerator/blocks/tileEntity/ExtremeHeatExchanger.java, src/main/java/goodgenerator/blocks/tileEntity/FuelRefineFactory.java, src/main/java/goodgenerator/blocks/tileEntity/LargeEssentiaGenerator.java, src/main/java/goodgenerator/blocks/tileEntity/LargeEssentiaSmeltery.java, src/main/java/goodgenerator/blocks/tileEntity/MultiNqGenerator.java, src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java, src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java, src/main/java/goodgenerator/blocks/tileEntity/UniversalChemicalFuelEngine.java, src/main/java/goodgenerator/blocks/tileEntity/YottaFluidTank.java, src/main/java/goodgenerator/blocks/tileEntity/base/GT_MetaTileEntity_LargeTurbineBase.java, src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12516
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12225
should fix nei diagram for large essentia smeltry, universal chem engine and neutron activator 
should fix occasional console error spam for CoAL
migrate to newer survival autoplace api
=> structure cleanup

src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer4.java, src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer5.java, src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
fix [GTNewHorizons/GT-New-Horizons-Modpack#14566](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14566). Not fully tested.
=> fix compact fusion energy consumption

src/main/java/goodgenerator/blocks/tileEntity/MultiNqGenerator.java
https://discord.com/channels/181078474394566657/522098956491030558/1183828190972608512
=> Fix crash with Nq Gen if coolant has just been depleted

src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputerPP.java, src/main/resources/assets/goodgenerator/lang/en_US.lang
Adjust batch size by parameter. Close [GTNewHorizons/GT-New-Horizons-Modpack#14996](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14996)
=> Batch mode for compact fusion MKIV-V

build.gradle, dependencies.gradle
May partially fix issues with mutemaster
=> [bs] update dependencies

src/main/java/goodgenerator/blocks/tileEntity/ComponentAssemblyLine.java
Enables batch mode functionality for the component assemblyline for lag reduction
=> Enable batch mode for component assemblyline

src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer1.java, src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer2.java, src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer3.java, src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer4.java, src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer5.java, src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
Complete [#224](https://github.com/GTNewHorizons/GoodGenerator/pull/224)
Close [https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14991](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14991)
=> Compact Fusions support buffer

src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
Any amount below the limit
Close [#15436](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15436)
=> Allow compact fusions to accept any amount of energy from energy hatches

src/main/java/goodgenerator/crossmod/thaumcraft/Research.java
rebalancing the recipe for https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/825 at request of @Dream-Master
=> update T1 diffusion cells to EV for the bee sucker

src/main/java/goodgenerator/blocks/tileEntity/ComponentAssemblyLine.java
Partially fixes GTNewHorizons/GT-New-Horizons-Modpack#15917, will make an additional PR on GT++ in a moment.
=> Allow wire cutter to toggle batch mode on Component Assembly line
