- src/main/java/goodgenerator/loader/RecipeLoader_02.java
- Make coil costs ~80% of what they would be if you made 64 reactors.
- Fix MK5 shenanigans (again)
- Add disassembly recipes for compact coils.
> Adjust compact coil recipes for balance.

- src/main/java/goodgenerator/loader/RecipeLoader.java
- src/main/java/goodgenerator/loader/RecipeLoader_02.java
- Replaced the LV-tier Soldering Alloy in Assembly Line recipes with a higher tier, more complex solder that fits progression better.
Requires https://github.com/GTNewHorizons/GTplusplus/pull/193. See that PR for more information.
> Replace Assline Solder in GoodGenerators Recipes

- dependencies.gradle
- src/main/java/goodgenerator/blocks/tileEntity/CoolantTower.java
- src/main/java/goodgenerator/crossmod/nei/ExtremeHeatExchangerHandler.java
- src/main/java/goodgenerator/loader/Loaders.java
- src/main/java/goodgenerator/loader/RecipeLoader_02.java
- src/main/java/goodgenerator/util/ItemRefer.java
- src/main/resources/assets/goodgenerator/lang/en_US.lang
another way to turn plasma into power.
the fusion generates plasma, then heat distilled water into supercritial steam (3x base power value than plasma) in EHE(extrem heat exchanger).
the plasma has higher fuel value can be processed more quickly
|fuel value (eu/mb)|speed (mb/s)|
|----|----|
|>200000|1500|
|200000~100000|1000|
|50000~10000|500|
|<10000|100|
it means the low power plasma like helium will become very slow in EHE.
the SC steam turbine can generate power from supercritial steam(1mb = 100eu). its optimal flow is the same as the normal steam optimal flow. it means it actually has higher output than regular plasma turbine with the same turbine.
2400L/t * 100 = 240000EU/t about 1.7x plasma power.
the price is the supercritial steam cause 10x damage to the turbine.
the SC steam …
> supercritial steam power cycle system

- src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/YOTTAHatch.java
Simply makes them tick once every 20 ticks instead of every tick. Testing showed 50% or more of tick time improvement, without any real noticeable usage difference.
> Rate-limit the YOTTAHatch to reduce their tick time.

- src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
Fusion reactors fail to check their structure correctly. This results in the need to always place the controller last. I implemented the same check as in the multiblock base to check the structure from time to time, or immedietly if you restart it.
> Use the same check as in multiblock base to check the structure

- src/main/java/goodgenerator/blocks/tileEntity/LargeEssentiaGenerator.java
LEG allows you to use only 1 essentia input hatch, because other places for hatches will be used for dynamo hatch, maintenance hatch and input hatch for liquid. So you cannot use multiple essentia type in 1 generator and multiple liquid type, but LGE allows you to do that by its own. Moreover, it cannot use more than 2 essentia per tick because of slow essentia providers (export busses doesn't work).
> Allow multiple hatches in Large Essentia Generator

- dependencies.gradle
Updated dependencies to prevent dupes bugs with stocking input bus
Fixes https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/62 and many undiscovered dupes too
> Fix dupe bugs with stocking input bus

- dependencies.gradle
- src/main/java/goodgenerator/loader/RecipeLoader_02.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11636
Other materials don't have such issue because they don't have autogenenerated gas EBF recipes. Dalisenite itself doesn't have `ANAEROBE_SMELTING` nor `NOBLE_GAS_SMELTING` tags, but `LuVTierMaterial`, which Dalisenite has as component, has `NOBLE_GAS_SMELTING` tag. So `DustLoader` generates gas EBF recipe, causing duplicated recipes. (https://github.com/GTNewHorizons/GoodGenerator/pull/88)
Modifying `Werkstoff#contains` will break many stuff, so I simply added back freezer recipe.
> Fix Dalisenite not having freezer recipe

- src/main/java/goodgenerator/loader/FuelRecipeLoader.java
Added new recipes for naq fuel 4 and 5 that have better conversion ratios between them and use higher tier materials. These additions aim to reduce the sheer amount of low tier items needed to make naq fuel and use less, but higher tier materials instead. 
There also are new recipes for the high density ingots that also follow this rule (they are in the following pr):
https://github.com/GTNewHorizons/bartworks/pull/218
Here is the google doc I used for my calculations. The first page contains the current recipes and the second page has the new ones.
https://docs.google.com/spreadsheets/d/1NtElMYIg9QAs6LcnT-XHwODBIteLxiE5jDWRcKQWpyc/edit?usp=sharing
These are the new recipes condensed into one image:
Please comment if you have any feedback or dm me on discord
> Add better naq fuel recipes to combat fusion spam

- src/main/java/goodgenerator/loader/RecipeLoader.java
- src/main/java/goodgenerator/main/GG_Config_Loader.java
Redo of https://github.com/GTNewHorizons/GoodGenerator/pull/62 because I messed up the original branch and now its gone. 
- Add a competitive alternative to helium plasma available early enough and strong enough to create real power diversity but not too much to make helium plasma really bad in comparison
- Make the previously useless/outclassed Mk1/2/3 Naq Fuels viable
- Make Naq Fuel progression earlier and more sensible
Enriched Naquadah recipe for Acid Naquadah Emulsion:
- Fluid input changed: 1000L Fluoroantimonic Acid -> 3000L Hydrofluoric Acid
- Enriched Naq input reduced: 32 -> 16
Naquadah Emulsion recipe:
- Quicklime input reduced: 32 -> 8
- Small pile of Antimony Trioxide removed
(Affects the naquadria path for Acid Naquadah Emulsion but I doubt anyone using naq fuel is gonna be …
> Naq Fuel 1,2,3 Changes

- dependencies.gradle
- src/main/java/goodgenerator/blocks/tileEntity/ComponentAssemblyLine.java
- src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
- src/main/java/goodgenerator/blocks/tileEntity/base/GT_MetaTileEntity_LongPowerUsageBase.java
- src/main/java/goodgenerator/items/MyMaterial.java
- src/main/java/goodgenerator/loader/ComponentAssemblyLineMiscRecipes.java
- src/main/java/goodgenerator/loader/RecipeLoader.java
- src/main/java/goodgenerator/loader/RecipeLoader_02.java
- src/main/java/goodgenerator/util/MaterialFix.java
- src/main/java/goodgenerator/util/StackUtils.java
- move `ComponentAssemblyLine` to `GT_MetaTileEntity_LongPowerUsageBase` to avoid duplicating code
- add a fast way to get tier material in `StackUtils`
- add some new materials
- use both gg alloy and gt++ alloy for component assembly casing
> clean the long power use base and add item util for tiered material

- src/main/java/goodgenerator/blocks/tileEntity/SupercriticalFluidTurbine.java
because obviously steam doesn't have pollution
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11873
> remove muffler from steam turbine tooltip

- src/main/java/goodgenerator/blocks/tileEntity/SupercriticalFluidTurbine.java
the origin value is 8x faster than normal turbine. it means a large tungstensteel turbine will break in 2-3 hours. after this buff the turbines can last 4x longer.
> make sc turbine damage 2x faster than normal turbine

- src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
- Simplified Fluoroantimonic Acid and P507 to their components, to minimize the amount of LCRs needed for these skips;
- Changed the last naqline skip to not be tier 4;
- Halved recipe times because these energy tiers are higher than the ones on the QFT's PR, which will also be changed in a similar way.
These naqline skips would still force a number of LCRs to stick around to create these intermediate fluids - the main thing that the QFT was designed to avoid - so I replaced them (Fluoroantimonic Acid and P507) with their elemental equivalents, which are Carbon, Fluorine, Antimony, Hydrogen and Oxygen. I left Phosphor out because P507 is used in tiny amounts, and the phosphor atom in a molecule of that is 1 in 54 atoms.
Additionally, I changed the last skip's tier to 3, instead of 4, …
> Tweak QFT Recipe Inputs and Tiers

- src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
Makes naquadria supersolid be given at tier 3 instead of tier 2 and turn enriched naq to use SimpleNaq catalyst instead of advanced one as its now one tier lower.
> Fix naquadria supersolid being given at tier 2 instead of 3

- dependencies.gradle
- src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
With the help of @GDCloudstrike the QFT's skip for naqlines has been reworked a bit to require less plasma and a single neutron activator being able to keep up with a maxed out QFT to prevent multi spam for it.
Values:
New Recipes:
Inert Naquadah
Inert Enriched Naquadah
Inert Naquadria
> Naqlines QFT Rebalance

- src/main/java/goodgenerator/blocks/tileEntity/ExtremeHeatExchanger.java
hotName can be null if recipe check never pass.
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12345. interesting issue number btw.
> guard against null hotName

- src/main/java/goodgenerator/loader/ComponentAssemblyLineRecipeLoader.java
The 64x power and time multiplier that I added previously ended up being too much of a nerf, causing the multi to become temporarily irrelevant.
This removes the power multiplier while still keeping the time multiplier.
> Remove 64x power multiplier for components in CoAL

- src/main/java/goodgenerator/loader/RecipeLoader_02.java
Fixes the research using the wrong item and causing overlap
> Fix compact mk5 research

- src/main/java/goodgenerator/loader/ComponentAssemblyLineRecipeLoader.java
The recipes were using molten attuned tengam which is not obtainable, changed it to purified tengam
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13516
> Fix tengam in component assemblyline

- src/main/java/goodgenerator/blocks/tileEntity/LargeEssentiaGenerator.java
As has been discussed in #magic-dev in the face of chochom's laser nuke on the LEG, we need to update this value to have a max at either UV or UHV, I have set it here for UV but I'm open to suggestions
> Buffing the LEG to UV for the LEG Laser nerf

- build.gradle
- src/main/java/goodgenerator/blocks/tileEntity/LargeEssentiaGenerator.java
This PR removes laser hatch support from the LEG. Multiamp hatches up to 64A will continue to be allowed.
several reasons:
- The multi is aimed at HV-ZPM while laser is always considered UV+ technology.
- Laser support on energy production is extremely unbalanced if the numbers are not carefully considered and limitted by something else (which is not the case here)
- people have figured out how to make up to 136 billion EU/t in ZPM in the extreme. Of course several orders of magnitude less would already be a big problem. by comparison on gets around 1 million eu/t from a single fusion reactor running helium plasma with a large plasma turbine in ZPM. (64A ZPM for one LEG will still be 8 million eu/t!)
- closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13792
> Remove laser support for LEG

- src/main/java/goodgenerator/loader/RecipeLoader_02.java
@Steelux8 This stops the SC steam value of Celestial Tungsten plasma being half of what it should be.
> Set SH steam output for plasmas to 0; remove bounds check.

- src/main/java/goodgenerator/loader/ComponentAssemblyLineRecipeLoader.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13953
Currently CoALs become a spam multi in endgame. The server I play on has ~40 at 8T eu/t each and they still bottleneck many crafts. This attempts to alleviate some of the spam without trivializing component crafts by reducing time multiplier over base to 48x from 64x.
> Buff CoAL recipe times to 48x base instead of 64x

- src/main/java/goodgenerator/blocks/tileEntity/ComponentAssemblyLine.java
Fixes the hint text for the multiblock preview on the Component Assembly Line being incorrect. (Hint 1 dot, etc.)
The hint dots in the preview now correctly correspond to what is given in the hint block descriptions
> CoAL Hint Text Fix

- src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
Their texture were sometimes not properly updated to fit the casing.
> Fix crafting input hatches texture in PrAss

- src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/YOTTAHatch.java
Using FluidStack limits extraction to INT32_MAX; use AEFluidStack to extract up to INT64_MAX.
Close https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/97
> Extract using AEFluidStack, not FluidStack

- src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14053
> Don't consume multiple amps for Precise Assembler if only one normal energy hatch is used

- src/main/java/goodgenerator/loader/RecipeLoader_02.java
Currently the only two sources of Tiberium are Void Miners or Space Mining (Or converting diamonds/firestone using Naquadah Fuels but that defeats the point). Tiberium is the primary bottleneck of Naqfuel, requiring dedicated space elevators of nothing but Space Mining modules to keep up with the demand.
This PR makes the Tiberium Dust + Naquadah Gas -> Tiberium Crystal recipe produce 1.2 crystals instead of 1.0, essentially allowing the player to convert Naquadah Gas into more Tiberium. Naquadah gas is already a fairly useless byproduct of Naqfuel, so this would help players keep up with the demand.
> Add a way to make more Tiberium using Naquadah Gas

- build.gradle
- src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12940
will also need to do this in GTNH lanth for mona/bastline stuff.
works correctly now:
> Add PA centrifuge recipe map to naq line recipe replacements

- src/main/java/goodgenerator/main/GG_Config_Loader.java
Increases Mark I burn time in the reactor by 200%, from 20 ticks to 60 ticks, essentially buffing it by 200%.
Does the same for Mark 2 by 250%, 20 ticks to 70 ticks.
Nobody uses the Mk1 and Mk2 fuels because the logistical complexity of setting up a full naquadah line and additional processing for the fuels themselves is vastly under-rewarded by the current fuel values, when the player can just do normal fusion for helium/tin plasma to get roughly equivalent amounts of power for no infrastructure investment.
Buffing the MKI and MKII numbers should make at least some players consider the early tier naquadah fuels.
As this affects balance:
**What goal is this change trying to achieve? What tier is it targeting?**
Naquadah Fuel MKI and MKII have such a massive upfront cost compared to other …
> Buff Mark I and Mark II naquadah fuels

- src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
the code was already mostly correct, but a simple flag was missing.
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14333
now works correctly (tested UV recipe with 64A IV hatch with IV or UV casings, both dont start now):
> No amperage OC for PrAss

- src/main/java/goodgenerator/blocks/tileEntity/UniversalChemicalFuelEngine.java
Due to the usage of `int`, UCFE cannot generate a large amount of energy, such as the ZPM 4096A. This pull request migrates the usage of `int` to `long`, utilizing TecTech's new power API.
> Make UCFE use TecTech's new power API

- src/main/java/goodgenerator/items/MyMaterial.java
Allows metastable og to be solidifed into screws, bolts, rings etc.
You need a fair amount of screws and there's not really a reason why you shouldn't be able to solidfy into that.
> Add more solidifier recipies for metastable oganesson

- src/main/java/goodgenerator/blocks/tileEntity/FuelRefineFactory.java
The multi passes structure checks without a maintenance hatch and clears all maintenance issues when placed, but does not prevent them from reappearing during processing. This is what e.g. the TecTech active transformer does to avoid maintenance issues.
> Stop maintenance issues cropping up on fuel refinery.

- src/main/java/goodgenerator/blocks/tileEntity/PreciseAssembler.java
Cannot use `filterValidMTEs` for `mDualInputHatches` since its signature is `ArrayList<IDualInputHatch>`
> Cleanup isValidMetaTileEntity again

- dependencies.gradle
- gradle.properties
- settings.gradle
- src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
- src/main/java/goodgenerator/main/GoodGenerator.java
1. Change to `GT_HatchElement.InputHatch.or(GT_HatchElement.InputBus)` instead of adding the input bus separately. This still allows for the crafting input bus and is mostly done to prevent the BlockRenderer preview from placing a gazillion input busses. 
2. Adds hatchItemFilterAnd to make survival autobuild use the required tier busses or higher. (Might be controlled by the adder as well but not for the preview)
3. Change the energy hatches to use anyOf instead of atLeast. This allows survival autobuild to place all 32 energy hatches provided they are in your inventory. I don't believe there's any use case where placing only 1 hatch is desired.
~~4. Bans input busses completely as they don't have any purpose. This does not affect the crafting input bus.~~
> Compact fusion structure fixes

- src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
Fixes the naq nugget recipe.
It was broken in https://github.com/GTNewHorizons/GoodGenerator/pull/232. Just got mixed up with another recipe by mistake.
Now all good:
> Fix naq nugget recipe

- src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
Fixes three bugs regarding compact fusion reactors.
The first and major fix is that compact fusion reactors now cannot skip fusion tiers, so for example a mk4 compact cannot do mk5 fusion recipes. 
The second, smaller fix, is that compacts can no longer overclock on-tier recipes (this was only a thing for mk5s).
The third fix is that the required eu/t in the scanner info no longer displays a negative number.
> Fix compact fusion tierskip, wrong OC and scanner info

- src/main/java/goodgenerator/loader/ComponentAssemblyLineRecipeLoader.java
Post-QFT, I am left with a surfeit of Styrene-Butadiene rubber.
The Assembly Line recipes for pumps allow both Styrene-Butadiene Rubber rings and Silicone Rubber rings, similarly the conveyors allow for either plate, using the `@ringAnySyntheticRubber` or `@plateAnySyntheticRubber` oredict entries. But the code to derive Component Assembly Line recipes only use the first oredict entry, so in the CoAL I can only use Silicone Rubber.
This changes that in the least invasive way I could see. As noted in the comment, it is a bit fragile, i.e., if the ordering in the oredict list changes it will probably stop working again. If y'all have alternative suggestions I'm all ears :-)
Screenshots of a couple of the added recipes:
> CoALs: Add missing styrene-butadiene variants for AssLine recipes.

- src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer1.java
- src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer2.java
- src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer3.java
- src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer4.java
- src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer5.java
- src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java
- src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputerPP.java
- Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15568
- Adjust EU capacity and power restriction per energy hatch: 
- - For MK4 and MK5, EU capacity per hatch is doubled; now the maximum total energy capacities of compacts are the same as their small versions
- - The maximum input power (with 32 energy hatches) is just enough to run any recipe within their capabilities
- Compacts perform overclocks correctly with https://github.com/GTNewHorizons/GT5-Unofficial/pull/2528
- Compacts will assume there are always 32 energy hatches when they are processing recipes and calculating avaliable EUt. imo this will make them less confusing. (When machine fails you realize you should install more energy hatches for it)
- Tooltips changes
> Fix compact fusions

- dependencies.gradle
- settings.gradle
- src/main/java/goodgenerator/blocks/tileEntity/FuelRefineFactory.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15704
> Fix naq fuel refinery coils not auto placeable in survival

- src/main/java/goodgenerator/blocks/tileEntity/LargeEssentiaGenerator.java
Fixes issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14104 by moving getPerAspectEnergy call into EU generation loop.
As an example, some sample data from supplying Ira with cryotheum as the coolant, over 60s+:
| Tier  | Expected Coolant Draw | Current Coolant Draw| This PR  |
|-------|:----------:|:---------:|--------|
| HV 4A | 0.9503 | 200.83  | 0.944  |
| EV 4A | 3.8014  |  203.27    | 3.8282 |
And with Adept hatches instead of novice:
| Tier  | Expected | Current | This PR |
|-------|----------|---------|-------|
| EV 4A | 1.907    |  200.42     | 1.99  |
| IV 4A | 7.6028   |   201.878      | 7.802 |
> Prevent LEG from drawing significantly higher amounts of coolant than expected

- src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15716
moderators are now applied only when it would do anything. Additionally, the check is now only performed once per second OR when it's about to ruin the product. There are some edge cases that would lead to the ceiling detection to fail, but IMO it's fairly rare (as long as your design is correct you should never run into this situation, or use moderators at all) and the tradeoff between mspt and edge case failing is worth it.
> bandaid fix for NA lag when off

- dependencies.gradle
- src/main/java/goodgenerator/blocks/tileEntity/NeutronActivator.java
Previously, the Neutron Activator GUI would use the generic MUI number formatting function to report its kinetic energy in appropriate units (k, M, G) depending on the amount of KE stored. However, this has proven impractical at the high end of the scale: any amount of energy between 1e9 and 1.1e9 eV would simply be reported as "1 GeV". This is insufficient granularity for the player to know whether it is ready to run a recipe. For instance, the Naquadria-Rich Solution recipe needs the KE to be between 1,050 MeV and 1,100 MeV.
This PR makes the GUI always report the energy in MeV, as this is the unit used in all NEI diagrams and probably the most relevant one to the player.
> Make the Neutron Activator UI always report kinetic energy in MeV.

- src/main/java/goodgenerator/blocks/tileEntity/EssentiaHatch.java
When the hatch ticks it checks around it for things that look like Thaumcraft pipes. Before this commit, if it happens that the first one it checks can't output to the hatch, it gives up instead of checking the others.
That behavior created weird bugs with two hatches adjacent, especially in the case where you have rotated the LEG, either with #249 or placing the controller facing up/down in the current release.
> Fix Essentia Input Hatch

- src/main/java/goodgenerator/loader/RecipeLoader_02.java
This PR merges the same items in different slots into one slot for assembly line recipes for yottank cells. This removes the need for excessive renaming of items. 
The motivation for this is that crafting EoH blocks requires high tier yottank cells. This means that there is a point in progression where, even if you never want to use yottanks, are forced to craft T2 fluid core, T2 fluid cell, then scan both and repeat for T3, all the way up to T7-8-9. Doing this while having to set up 3-4 rename patterns per tier is extremely tedious, and by this point in progression the renaming mechanic is entirely played out and not really fun anymore.
All recipe costs remain unchanged, I simply merged the stacks together. The only exception is 2 stacks of 64 large titanium fluid pipes, which I merged …
> Deduplicate assline recipes for yottank cells

- src/main/java/goodgenerator/blocks/tileEntity/LargeEssentiaGenerator.java
Previously, the Large Essentia Generator could only be rotated to two possible orientations: either with the main structure below the controller (if the face of the controller was pointed towards any cardinal direction), or with the structure on the *south* side of the controller (if the face of the controller was pointing up or down). This was caused by the LEG attempting to do its own rotation logic (??) instead of inheriting the one from `GT_MetaTileEntity_EnhancedMultiblockBase` and reimplementing it poorly.
This PR makes it so that the LEG can be rotated to any direction, allowing for more varied and compact setups. Flipping the LEG is still allowed, although it makes no functional difference (since the structure is symmetrical).
> LEG rotation fix

- src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/YOTTAHatch.java
- src/main/java/goodgenerator/blocks/tileEntity/YottaFluidTank.java
- Remove all unnecessary BigInteger allocations where possible
- Store the fluid types as FluidStacks instead of Strings, this reduces the constant lookups into the fluid registry
- Cache the fluid tank info array
- Big one: only update once per second (20 ticks) instead of every tick, the output fill rate has been bumped 20x to compensate - but bigger input hatches might be needed if they were barely keeping up before.
> YOTTank performance refactor

- src/main/java/goodgenerator/blocks/tileEntity/UniversalChemicalFuelEngine.java
The Universal Chemical Fuel Engine is an LuV powergen multiblock that takes in fuel and Combustion Promoter, and consumes all that it finds in the input hatches every second. If it consumes more fuel and has nowhere to send the EU, because the dynamo's buffer, it explodes. This mechanic causes at least two problems:
- If the multi is turned on with some amount of fuel inside, from setting up the regulators and then powering on the UCFE after some time, it will instantly explode;
- On world load, if the EU is not drawn out fast enough, the UCFE will run until the buffer is full and just explode.
I added an explosion safety counter, which counts to 200 ticks (10 seconds). Every time the machine is turned off, or the world is reloaded, the counter goes back to 0. During these 10 seconds, the …
> Prevent Instant UCFE Explosions
